docs: IDS cleanup and replace with DSP
eclipse-edc/Samples pull request #111
Opened 2023-09-06 13:59 UTC by majadlymhmd

## What this PR changes/adds

remove the leftovers of IDS dependencies and replace them with DSP . 
remove the IAIS dependency . 
## Why it does that

The IDS is no longer needed
## Further notes

## Linked Issue(s)

refers #103 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2023-09-06 16:49 UTC, ndr-brt approved these changes

2023-09-06 16:49 UTC, ndr-brt commented on transfer/transfer-06-consumer-pull-http/http-pull-consumer/consumer-configuration.properties
> +edc.dsp.id=urn:connector:consumer
this property does not exist anymore, it can be removed from all the configuration files, `edc.participant.id` will be enough

2023-09-11 09:07 UTC, juliapampus requested changes

2023-09-18 08:18 UTC, juliapampus approved these changes

2023-09-18 08:18 UTC, merged